name: Python CI with TensorFlow-CPU and Dash

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.1'  # Используем Python 3.12.1

    - name: Upgrade pip, setuptools, and wheel
      run: |
        python -m pip install --upgrade pip setuptools wheel

    - name: Install dependencies
      run: |
        pip install tensorflow-cpu numpy pytest # Устанавливаем последнюю версию TensorFlow для CPU
        pip install dash
        pip install plotly
        pip install pylint  # Устанавливаем pylint для линтинга

    - name: Run pylint
      run: |
        pylint **/*.py  # Проверка всех .py файлов в проекте

    - name: Run tests
      run: |
        if [ -d "tests" ]; then
          pytest tests  # Запуск тестов, если они есть
        else
          echo "No tests found, skipping test run"
        fi

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to server
      run: |
        echo "Deploying to server..."
